export const LINE_COLORS: Record<string, string> = {
  red: '#EE1C25',
  blue: '#0072BC',
  yellow: '#FFCB05',
  green: '#00B050',
  violet: '#8E3294',
  pink: '#F5A1C8',
  orange: '#F7941D',
  magenta: '#A62C84',
  grey: '#808285',
  aqua: '#00AFAD',
  rapid: '#006CB7',
  bluebranch: '#0072BC',
  greenbranch: '#00B050',
  pinkbranch: '#F5A1C8',
}

export const LINE_NAMES: Record<string, string> = {
  red: 'Red Line',
  blue: 'Blue Line',
  yellow: 'Yellow Line',
  green: 'Green Line',
  violet: 'Violet Line',
  pink: 'Pink Line',
  orange: 'Airport Express',
  magenta: 'Magenta Line',
  grey: 'Grey Line',
  aqua: 'Aqua Line',
  rapid: 'Rapid Metro',
  bluebranch: 'Blue Line (Vaishali)',
  greenbranch: 'Green Line (Branch)',
  pinkbranch: 'Pink Line (Branch)',
}
